from pathlib import Path
from datetime import datetime


def generate_clinician_report(
    image_name,
    quality_result,
    feature_result,
    confidence,
    
    output_dir,
    visit_comparison=None,
):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    report_path = output_dir / f"report_{Path(image_name).stem}.txt"

    lines = []
    lines.append("QadamCare AI - Clinician Screening Support Report")
    lines.append("=" * 60)
    lines.append(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Image name: {image_name}")
    lines.append("")

    lines.append("Image Quality Assessment")
    lines.append("-" * 30)
    lines.append(f"Status: {quality_result['status']}")

    for key, value in quality_result["metrics"].items():
        lines.append(f"{key}: {value}")

    if quality_result["blockers"]:
        lines.append("")
        lines.append("Retake reasons:")
        for item in quality_result["blockers"]:
            lines.append(f"- {item}")

    if quality_result["warnings"]:
        lines.append("")
        lines.append("Warnings:")
        for item in quality_result["warnings"]:
            lines.append(f"- {item}")

    lines.append("")
    lines.append("AI Ulcer Segmentation Summary")
    lines.append("-" * 30)
    lines.append(f"Possible visible ulcer-like regions: {feature_result['number_of_lesions']}")
    lines.append(f"Total predicted wound area: {feature_result['total_area_pixels']} pixels")
    lines.append(f"Average model confidence: {round(confidence, 4)}")

    lines.append("")
    lines.append("Lesion Details")
    lines.append("-" * 30)

    if feature_result["lesions"]:
        for lesion in feature_result["lesions"]:
            lines.append(
                f"Lesion {lesion['lesion_id']}: "
                f"estimated area={lesion['area_pixels']} pixels, "
                f"confidence={round(lesion['mean_confidence'] * 100, 1)}%, "
                f"clinical meaning=visible ulcer-like region detected"
                
            )
    else:
        lines.append("No visible ulcer-like region detected by the model.")

    if visit_comparison is not None:
        lines.append("")
        lines.append("Visit-to-Visit Comparison")
        lines.append("-" * 30)
        lines.append(f"Trend status: {visit_comparison['status']}")
        lines.append(f"Change in area: {visit_comparison['change_pixels']} pixels")
        lines.append(f"Change percentage: {visit_comparison['change_percent']}%")
        lines.append(f"Interpretation: {visit_comparison['message']}")

    lines.append("")
    lines.append("Clinical Safety Statement")
    lines.append("-" * 30)
    lines.append(
        "This output is generated by an educational engineering prototype. "
        "It is intended to support visual screening and documentation only. "
        "It is not a medical diagnosis, does not assess infection or severity, "
        "and must be reviewed by a qualified healthcare professional."
    )

    with open(report_path, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))

    return report_path